# Generated by Django 4.2 on 2024-08-24 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pystock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcode',
            name='trade_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='交易日期'),
        ),
    ]
