# Generated by Django 4.2 on 2024-08-25 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pystock', '0002_alter_testcode_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='trade_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='交易日期'),
        ),
        migrations.AlterModelTable(
            name='historyprice',
            table='HistoryPrice',
        ),
    ]
