# Generated by Django 4.2 on 2024-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pystock', '0003_alter_historyprice_trade_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyprice',
            name='down_limit',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='跌停价'),
        ),
        migrations.AddField(
            model_name='historyprice',
            name='up_limit',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='涨停价'),
        ),
    ]
