# Generated by Django 4.2 on 2024-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pystock', '0004_historyprice_down_limit_historyprice_up_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeIsOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='', max_length=16, verbose_name='交易所')),
                ('cal_date', models.CharField(default='', max_length=32, verbose_name='日历日期')),
                ('is_open', models.CharField(default='', max_length=8, verbose_name='是否交易')),
                ('pretrade_date', models.CharField(default='', max_length=32, verbose_name='上个交易日')),
            ],
            options={
                'db_table': 'TradeIsOpen',
            },
        ),
    ]
