# Generated by Django 4.2 on 2024-08-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pystock", "0005_tradeisopen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyprice",
            name="trade_date",
            field=models.DateField(verbose_name="交易日期"),
        ),
    ]
