# Generated by Django 4.2 on 2024-08-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pystock", "0006_alter_historyprice_trade_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradeisopen",
            name="cal_date",
            field=models.DateField(default="", max_length=32, verbose_name="日历日期"),
        ),
        migrations.AlterField(
            model_name="tradeisopen",
            name="pretrade_date",
            field=models.DateField(default="", max_length=32, verbose_name="上个交易日"),
        ),
    ]
