# Generated by Django 3.0.6 on 2024-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestBlog',
            fields=[
                ('author', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=18)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(blank=True, default='2000-01-01')),
                ('info', models.TextField(blank=True)),
                ('img1', models.ImageField(upload_to='static/images/')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
